Saving the first high beam detected frame in the working directory
sakshamsaxena/ocv-demo pull request #1
Opened 2017-02-14 20:28 UTC by samdish

2017-02-15 11:40 UTC, samdish commented
Added the required changes.

2017-02-16 07:20 UTC, sakshamsaxena commented on Core.cpp
> +			detected_image = frame; //save detected frame;
The `frame` here is cropped etc. Not what we need to save. `detected_image` should ideally be assigned after line 43.

2017-02-16 07:20 UTC, sakshamsaxena commented on Core.cpp
> +			sprintf(file,"Image_%d.jpg",count);  //save files with different names using 'count'
`file` isn't defined anywhere I think. Also, C++ has direct string concatenation with `+` operator. Can probably write this as `string file = "Image_"+to_string(count)+".jpg";`

2017-02-16 07:20 UTC, sakshamsaxena commented on Core.cpp
> +			imwrite(file,image);
`detected_image` not `image` bro

2017-02-16 08:39 UTC, samdish commented on Core.cpp
> +			sprintf(file,"Image_%d.jpg",count);  //save files with different names using 'count'
Went through a few links on stack overflow, and find that sprintf is the standard that everyone follows.. Can experiment with '+' as well.

2017-02-16 08:43 UTC, samdish commented on Core.cpp
> +			imwrite(file,image);
Oh ya! But you get what I meant: p

2017-02-16 10:27 UTC, samdish commented on Core.cpp
> +			detected_image = frame; //save detected frame;
By using it after line 43, we'll end up saving every frame that we capture.

2017-02-16 14:02 UTC, sakshamsaxena commented on Core.cpp
> +			detected_image = frame; //save detected frame;
We'll only save it when we enter the `if` block, that is, only on detection. It'll be the original unaltered frame. We only need to keep a copy of every unaltered frame, and it'll only be saved on detection. Right now, you've frame, original_frame, detected_frame. We could instead simply do `detected_frame = frame` above and and then use that directly in `imwrite`.

2017-02-16 14:06 UTC, sakshamsaxena requested changes

2017-02-16 14:06 UTC, sakshamsaxena commented on Core.cpp
> +			detected_image = frame; //save detected frame;
Reconsider the flow man. You'll get it.

2017-02-17 13:42 UTC, sakshamsaxena approved these changes

2017-02-17 13:42 UTC, merged